pre-commit: use "python3" for Black hook
When trying to run pre-commit on my system with Python 3.13, I get:

    An unexpected error has occurred: CalledProcessError: command: ('/usr/bin/python', '-mvirtualenv', '/home/smarchi/.cache/pre-commit/repo19s8spzi/py_env-python3.12', '-p', 'python3.12')
    return code: 1
    stdout:
        RuntimeError: failed to find interpreter for Builtin discover of python_spec='python3.12'

Fix this by specifying "python3" as the language version, instead of the
specific "python3.12".  Not sure why I used "python3.12" in the first
place.

Change-Id: I42ee6885dfaba30980ba514e7df324fa84d38d37
Signed-off-by: Simon Marchi <simon.marchi@efficios.com>