bt benchmark: Add further ignored commits
ade5c95e2a4f90f839f222fc1a66175b3b199922 and
30341532906d62808e9d66fb115f5edb4e6f5706 fail in the xenial rootfs,
unable to configure with the following error:

```
configure: error: elfutils >= 0.154 is required to use the debug info
feature. You can disable this feature using --disable-debug-info.
```

The rootfs has elfutils, libelf1, and libelf1-dev at a version >=
0.154 and I don't intend to investigate further.

@see https://lava-master-03.internal.efficios.com/scheduler/job/138
@see https://lava-master-03.internal.efficios.com/scheduler/job/144

006c5ffb42f32e802136e3c27a63accb59b4d6c4 and
88488ff5bdcd7679ff1f04fe6cff0d24b4f8fc0c fail to compile with the
following error:

```
param-validation.c:226:30: error: BT_VALUE_MAP_FOREACH_ENTRY_CONST_STATUS_MEMORY_ERROR undeclared
```

@see https://lava-master-03.internal.efficios.com/scheduler/job/136
@see https://lava-master-03.internal.efficios.com/scheduler/job/139

Further commits were added grouped in to two sections: Issues with
elfutils, and other build problems.

Based on jobs ~150-229 on lava-master-03

Change-Id: Ia6a7d60a474a53dd5395ee0cf133b43d3df7ceff