bt benchmark: Ignore commit ae466a6e1b856d96cf5112a371b4df2b732503ec
The commit fails to build. See
https://lava-master-03.internal.efficios.com/scheduler/job/133

```
param-validation.c: In function 'validate_map_value':
param-validation.c:226:30: error: 'BT_VALUE_MAP_FOREACH_ENTRY_CONST_STATUS_MEMORY_ERROR' undeclared (first use in this function)
  if (foreach_entry_status == BT_VALUE_MAP_FOREACH_ENTRY_CONST_STATUS_MEMORY_ERR
param-validation.c:226:30: note: each undeclared identifier is reported only once for each function it appears in
Makefile:466: recipe for target 'param-validation.lo' failed
```

Change-Id: I30f824fde526ed52f0427e233d808780f19d527a